# FILE CONTAINS ALL THE LIBRARIES WE NEED ON THE ROBOT
#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2024.1.1.3"

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = ["phoenix6"]

# Other pip packages to install
requires = [
    "robotpy-commands-v2==2024.0.0b4"

]
