# motors and robot devices
FRONT_RIGHT_ID = 1
FRONT_LEFT_ID = 2
BACK_LEFT_ID = 3
BACK_RIGHT_ID = 4
IMU_ID = 5

ARM_LEFT_ID = 6
ARM_RIGHT_ID = 7

INTAKE_MOTOR_ID = 8

SHOOTER_UPPER_MOTOR_ID = 9
SHOOTER_LOWER_MOTOR_ID = 10

ARM_IMU_ID = 11


# controlers
CONTROLLER_ID = 0