# motors and robot devices
FRONT_RIGHT_ID = 1
FRONT_LEFT_ID = 2
BACK_LEFT_ID = 3
BACK_RIGHT_ID = 4

SHOOTER_MOTOR_ID = 6
INTAKE_MOTOR_ID = 7

ARM_LEFT_ID = 10
ARM_RIGHT_ID = 11
ARM_IMU_ID = 12

CLIMB_LEFT_ID = 8
CLIMB_RIGHT_ID = 9
# sensors
IMU_ID = 5

# controlers
CONTROLLER_ID = 0